apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcomforters-kitchen
  namespace: production
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
