apiVersion: v1
kind: Service
metadata:
  name: dcomforters-kitchen-svc
  namespace: production
  labels:
    app: dcomforters-kitchen
spec:
  selector:
    app: dcomforters-kitchen
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32500
  type: NodePort
